---
language: php

dist: trusty

global:
  env:
    - ANSIBLE_ROLES_PATH=tests/roles

env:
  - ANSIBLE_REQUIREMENTS=tests/roles/composer_requirements.yml ANSIBLE_PLAYBOOK=tests/playbooks/composer.yml
  - ANSIBLE_REQUIREMENTS=tests/roles/phar_requirements.yml ANSIBLE_PLAYBOOK=tests/playbooks/phar.yml

install:
  - make deps-ansible
  # TODO: investigate why we need to install this separately, as it should be
  # covered by the deps above.
  - pip install --upgrade pip
  - pip install --user yaml
  - make ansible

script:
  # Bootstrap Drumkit
  - ". d"

  # Run playbook tests
  - sudo make ansible-playbook-test

  # Check if drush is installed and working.
  - drush --version

