---
language: python
python: "2.7"

dist: trusty

global:
  env:
    - ANSIBLE_ROLES_PATH=tests/roles

env:
  - ANSIBLE_REQUIREMENTS=tests/roles/composer_requirements.yml ANSIBLE_PLAYBOOK=tests/playbooks/composer.yml
  - ANSIBLE_REQUIREMENTS=tests/roles/phar_requirements.yml ANSIBLE_PLAYBOOK=tests/playbooks/phar.yml

install:
  - make deps-ansible
  - pip install pyyaml jinja2
  - make ansible

script:
  # Bootstrap Drumkit
  - ". d"

  # Run playbook tests
  - make ansible-playbook-test

  # Check if drush is installed and working.
  - drush --version

