---
language: php

dist: trusty
sudo: false

addons:
  apt:
    packages:
    - python-yaml
    - python-jinja2

env:
  - ANSIBLE_REQUIREMENTS=tests/composer_requirements.yml ANSIBLE_PLAYBOOK=tests/composer_playbook.yml
  - ANSIBLE_REQUIREMENTS=tests/phar_requirements.yml ANSIBLE_PLAYBOOK=tests/phar_playbook.yml

install:
  - make ansible

script:
  # Bootstrap Drumkit
  - ". d"

  # Run playbook tests
  - make ansible-playbook-test

  # Check if drush is installed and working.
  - drush --version

